### ISSUE TITLE
Loading the cog 

### ISSUE THREAD

**Issue by XxPoNaGeXx** [Peyton2017/Discord-RPG#1]
Loaded the cog and got this error:

**Comment by XxPoNaGeXx** [comment]
Exception in command 'help'
Traceback (most recent call last):
  File "lib/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "lib/discord/ext/commands/bot.py", line 115, in _default_help_command
    pages = bot.formatter.format_help_for(ctx, command)
  File "lib/discord/ext/commands/formatter.py", line 291, in format_help_for
    return self.format()
  File "lib/discord/ext/commands/formatter.py", line 315, in format
    signature = self.get_command_signature()
  File "lib/discord/ext/commands/formatter.py", line 205, in get_command_signature
    params = cmd.clean_params
  File "lib/discord/ext/commands/core.py", line 240, in clean_params
    result.popitem(last=False)
KeyError: 'dictionary is empty'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "lib/discord/ext/commands/bot.py", line 846, in process_commands
    yield from command.invoke(ctx)
  File "lib/discord/ext/commands/core.py", line 374, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "lib/discord/ext/commands/core.py", line 54, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: KeyError: 'dictionary is empty'

**Comment by deadjak** [comment]
did you modify anything in the cog?

**Comment by Fearzie** [comment]
(Pretty much a year later and not even sure if this project is still active but...) I also get this issue on an unmodified version of this cog.

**Comment by Peyton2017** [comment]
> (Pretty much a year later and not even sure if this project is still active but...) I also get this issue on an unmodified version of this cog.

Hello Fearzie. I had gotten very, very busy. Hence no replies. If you'd like to chat about my upcoming open-source fully customizable RPG, feel free to join my personal Discord - https://discord.gg/MgJgRAz

My username is ZorE / Banthis. Sorry about these issues. I don't think I'll be fixing them, as I'm working on a more flexable RPG (With img gen.)

I also want to create a top-down tilemap where players can actually explore a world, and interact with things. And yes, within Discord.
