### ISSUE TITLE
Discord-RPG dd error 

### ISSUE THREAD

**Issue by STORMFIRE007** [Peyton2017/Discord-RPG#3]
I am facing this error while installing discord rpg dd:
https://gist.github.com/anonymous/867f259907f37acd37ed94830cb6e436

**Comment by bc1bb** [comment]
same : 
```
[14/07/2018 13:25] ERROR owner load 74: [Errno 2] No such file or directory: 'data/alcher/players.json'
Traceback (most recent call last):
  File "C:\Users\paill\potatojuice\Red-DiscordBot\cogs\owner.py", line 65, in load
    self._load_cog(module)
  File "C:\Users\paill\potatojuice\Red-DiscordBot\cogs\owner.py", line 948, in _load_cog
    self.bot.load_extension(mod_obj.__name__)
  File "lib\discord\ext\commands\bot.py", line 738, in load_extension
    lib.setup(self)
  File "C:\Users\paill\potatojuice\Red-DiscordBot\cogs\dd.py", line 878, in setup
    check_folders()
  File "C:\Users\paill\potatojuice\Red-DiscordBot\cogs\dd.py", line 866, in check_folders
    transfer_info()
  File "C:\Users\paill\potatojuice\Red-DiscordBot\cogs\dd.py", line 869, in transfer_info
    players = fileIO("data/alcher/players.json", "load")
  File "C:\Users\paill\potatojuice\Red-DiscordBot\cogs\utils\dataIO.py", line 60, in _legacy_fileio
    return self.load_json(filename)
  File "C:\Users\paill\potatojuice\Red-DiscordBot\cogs\utils\dataIO.py", line 32, in load_json
    return self._read_json(filename)
  File "C:\Users\paill\potatojuice\Red-DiscordBot\cogs\utils\dataIO.py", line 45, in _read_json
    with open(filename, encoding='utf-8', mode="r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/alcher/players.json'
Traceback (most recent call last):
  File "C:\Users\paill\potatojuice\Red-DiscordBot\cogs\owner.py", line 65, in load
    self._load_cog(module)
  File "C:\Users\paill\potatojuice\Red-DiscordBot\cogs\owner.py", line 948, in _load_cog
    self.bot.load_extension(mod_obj.__name__)
  File "lib\discord\ext\commands\bot.py", line 738, in load_extension
    lib.setup(self)
  File "C:\Users\paill\potatojuice\Red-DiscordBot\cogs\dd.py", line 878, in setup
    check_folders()
  File "C:\Users\paill\potatojuice\Red-DiscordBot\cogs\dd.py", line 866, in check_folders
    transfer_info()
  File "C:\Users\paill\potatojuice\Red-DiscordBot\cogs\dd.py", line 869, in transfer_info
    players = fileIO("data/alcher/players.json", "load")
  File "C:\Users\paill\potatojuice\Red-DiscordBot\cogs\utils\dataIO.py", line 60, in _legacy_fileio
    return self.load_json(filename)
  File "C:\Users\paill\potatojuice\Red-DiscordBot\cogs\utils\dataIO.py", line 32, in load_json
    return self._read_json(filename)
  File "C:\Users\paill\potatojuice\Red-DiscordBot\cogs\utils\dataIO.py", line 45, in _read_json
    with open(filename, encoding='utf-8', mode="r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/alcher/players.json'
```
